services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    profiles:
      - agent
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  model-loader:
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=ollama:11434
    entrypoint: ["/bin/sh"]
    command: ["-c", "ollama pull qwen2.5-coder:3b-instruct-q4_K_M && echo 'Model loaded successfully'"]
    profiles:
      - agent

  workflow-documenter:
    build:
      context: ./ai.documenter
      dockerfile: Dockerfile
    depends_on:
      model-loader:
        condition: service_completed_successfully
    volumes:
      - .:/workspace
    environment:
      MODEL_RUNNER_BASE_URL: http://ollama:11434/v1
      CHAT_MODEL_ID: qwen2.5-coder:3b-instruct-q4_K_M
      SYSTEM_INSTRUCTIONS: |
        You are an expert in GitHub Actions workflows and technical documentation.
        Your task is to analyze GitHub Actions workflow YAML files and create comprehensive, well-structured markdown documentation.
        
        The documentation should include:
        - A clear title with the workflow name
        - Metadata (workflow file name, last generated timestamp)
        - Trigger events (on: push, pull_request, workflow_dispatch, etc.) with all configuration details
        - Environment variables defined at workflow level
        - All jobs with their configurations
        - For each job: name, runs-on, strategy (if matrix build), and dependencies
        - All steps in each job with action names or commands
        - Any inputs, outputs, or with parameters for steps
        
        Format the documentation using proper markdown with headers, lists, and code blocks.
        Be concise but comprehensive. Use tables for complex data where appropriate.
        
      USER_MESSAGE: |
        Please analyze this GitHub Actions workflow YAML file and generate comprehensive markdown documentation.
        
        Structure the documentation with:
        1. A header with the workflow name (from the 'name' field)
        2. Metadata section with the workflow file name
        3. Last Generated timestamp in UTC
        4. Triggers section explaining when the workflow runs
        5. Environment variables section (if any)
        6. Jobs section with detailed breakdown of each job
        7. For each job, list all steps with their actions or commands
        
        Make sure to handle:
        - Matrix builds in strategy
        - Conditional steps (if: conditions)
        - Job dependencies (needs:)
        - Multiple trigger types
        
        Generate clear, professional documentation that would help developers understand this workflow.
    
    profiles:
      - agent

volumes:
  ollama_data:

x-github-agent:
  name: workflow-documenter
  description: Automatically generates markdown documentation for GitHub Action workflows using AI
  triggers:
    - on: workflow_file_changed
      paths:
        - '.github/workflows/*.yml'
        - '.github/workflows/*.yaml'
  actions:
    - service: workflow-documenter
      description: Generate AI-powered documentation for modified workflow files

